### PR TITLE
fix: Update KFP Controller Python image to Ubuntu/python rock

### LINKED ISSUE #487: `kfp-profile-controller` python not found
### Bug Description

`kfp-profile-controller` python not found

### To Reproduce

```bash
juju deploy kubeflow --channel 1.8/stable --trust
```

### Environment

Juju 3.1/stable
Microk8s 1.30/stable
Kubeflow 1.8/stable

### Relevant Log Output

```shell
# ----- Juju status
juju status --color| grep -vE "active|started"                                                                                                                                                                                                      g: Sat Jun  1 01:07:22 2024

Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.1.8    unsupported  01:07:23Z

App                        Version                  Status       Scale  Charm                    Channel          Rev  Address         Exposed  Message
katib-db                   8.0.35-0ubuntu0.22.04.1  waiting          1  mysql-k8s                8.0/stable       127  10.152.183.247  no       installing agent
katib-db-manager                                    waiting          1  katib-db-manager         0.16/stable      411  10.152.183.199  no       installing agent
kfp-persistence                                     waiting          1  kfp-persistence          2.0/stable      1291  10.152.183.221  no       installing agent
kfp-profile-controller                              waiting          1  kfp-profile-controller   2.0/stable      1278  10.152.183.22   no       installing agent
kfp-ui                                              maintenance      1  kfp-ui                   2.0/stable      1285  10.152.183.45   no       Reconciling charm: executing component relation:ingress

Unit                          Workload     Agent  Address     Ports          Message
katib-db-manager/0*           waiting      idle   10.1.67.22                 Waiting for relational-db data
katib-db/0*                   maintenance  idle   10.1.67.23                 Initialising mysqld
kfp-persistence/0*            maintenance  idle   10.1.67.30                 Reconciling charm: executing component container:persistenceagent
kfp-profile-controller/0*     waiting      idle   10.1.67.32                 [container:kfp-profile-controller] Waiting for Pebble services (kfp-profile-controller).  If this persists, it could ...

# ----- Logs 
unit-kfp-profile-controller-0: 00:59:17 INFO unit.kfp-profile-controller/0.juju-log Executing component: 'container:kfp-profile-controller'
unit-kfp-profile-controller-0: 00:59:17 ERROR unit.kfp-profile-controller/0.juju-log execute_components caught unhandled exception when executing configure_charm for container:kfp-profile-controller
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/charmed_kubeflow_chisme/components/charm_reconciler.py", line 92, in reconcile
    component_item.component.configure_charm(event)
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/charmed_kubeflow_chisme/components/component.py", line 50, in configure_charm
    self._configure_unit(event)
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/charmed_kubeflow_chisme/components/pebble_component.py", line 131, in _configure_unit
    self._update_layer()
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/charmed_kubeflow_chisme/components/pebble_component.py", line 142, in _update_layer
    container.replan()
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/ops/model.py", line 1915, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/ops/pebble.py", line 1680, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-kfp-profile-controller-0/charm/venv/ops/pebble.py", line 1761, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "kfp-profile-controller" (cannot start service: exec: "python": executable file not found in $PATH)
----- Logs from task 0 -----
2024-06-01T00:59:17Z ERROR cannot start service: exec: "python": executable file not found in $PATH
-----
unit-kfp-profile-controller-0: 00:59:18 INFO unit.kfp-profile-controller/0.juju-log HTTP Request: GET https://10.152.183.1/apis/apiextensions.k8s.io/v1/customresourcedefinitions "HTTP/1.1 200 OK"
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by orfeas-k**
Update the image to a Canonical maintained ROCK in order to fix #487 and
reduce the number of CVEs.

#### Testing
```bash
juju deploy metacontroller-operator --channel 3.0/stable --trust
juju deploy minio --channel ckf-1.8/stable
juju deploy kfp-profile-controller --channel 2.0/stable --trust --base ubuntu@20.04
juju relate kfp-profile-controller minio
juju status --watch 1s
# take a look at juju status or logs of kfp-profile-controller and verify that the issue's status and logs are there
# then refresh to this PR's
juju refresh kfp-profile-controller --channel 2.0/edge/pr-501
# verify that the workload starts and charm goes to `active`
kubectl -n <namespace> logs kfp-profile-controller-0 -c kfp-profile-controller | grep -i executable
```

Closes #487

### CODE REVIEW

**Comment by NohaIhab** [comment]
changes LGTM but let's update the branch once #500 is merged to unblock the CI

**Comment by NohaIhab** [comment]
I saw [your comment](https://github.com/canonical/kfp-operators/issues/487#issuecomment-2149535225). We need to test it manually in this case. Can you add some test instructions? @orfeas-k

**Comment by orfeas-k** [comment]
The issue for the tests https://github.com/canonical/kfp-operators/issues/502

**Comment by NohaIhab** [comment]
Tested with the instructions, LGTM.
The CI is failing with istio-pilot in error tho :/ can you take a look? It's certainly not related to your change but we still need the tests to pass

**Review by NohaIhab — APPROVED** [review]
CI was just flaky, let's file an issue for that if we can get some logs
thanks @orfeas-k

**Comment by orfeas-k** [comment]
Thanks @NohaIhab, filed https://github.com/canonical/kfp-operators/issues/504

**Pull request merged**
